<a href="https://colab.research.google.com/github/ndenizkoroglu/-automation-test-repo/blob/main/1_Load_save_every_format_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Farklı formatları yükle ve kaydet

## CSV dosyaları

Greenweez'de Veri Analisti olarak çalışıyorsunuz ve pazarlama ekibinden biri, bazı sorunlar yaşadıkları için `gwz_orders_samples_other_format.csv` dosyasını açmanıza yardım etmenizi istiyor.

[gwz_orders_samples_other_format.csv](https://drive.google.com/file/d/1yhqMnjAkbSjenpTPZFwkPoeCZY_wfimH/view?usp=drive_link) dosyasını colab'a içe aktarın ve `df_orders` veri çerçevesine yükleyin.

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd

df_orders = pd.read_csv(
    "/content/drive/MyDrive/Colab Notebooks/gwz_orders_samples_other_format.csv"
)

df_orders.head()

  \tdate_date\torders_id\tcustomers_id\tcountry\tdepartment\ttotal_quantity\ttotal_turnover
0   0\t2019-01-01\t571\t560\tFRANCE\t77.0\t52\t92.71
1   1\t2019-01-01\t287\t282\tFRANCE\t17.0\t19\t97.94
2   2\t2019-01-01\t113\t113\tFRANCE\t50.0\t20\t94.15
3    3\t2019-01-01\t519\t510\tFRANCE\t22.0\t8\t73.78
4    4\t2019-01-01\t224\t222\tFRANCE\t13.0\t2\t27.99

In [5]:
df_orders = pd.read_csv(
    "/content/drive/MyDrive/Colab Notebooks/gwz_orders_samples_other_format.csv",
    sep=";"
)

df_orders.head()

  \tdate_date\torders_id\tcustomers_id\tcountry\tdepartment\ttotal_quantity\ttotal_turnover
0   0\t2019-01-01\t571\t560\tFRANCE\t77.0\t52\t92.71
1   1\t2019-01-01\t287\t282\tFRANCE\t17.0\t19\t97.94
2   2\t2019-01-01\t113\t113\tFRANCE\t50.0\t20\t94.15
3    3\t2019-01-01\t519\t510\tFRANCE\t22.0\t8\t73.78
4    4\t2019-01-01\t224\t222\tFRANCE\t13.0\t2\t27.99

In [6]:
df_orders.to_csv(
    "/content/drive/MyDrive/Colab Notebooks/gwz_orders_samples_other_format_clean.csv",
    index=False
)

Bu verilerde bir sorun mu var?
`df_orders`'ı görüntüleyin ve bu sorunu nasıl çözebileceğinizi öğrenmek için [belgelere](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) bakın.

In [7]:
df_orders = pd.read_csv(
    "/content/drive/MyDrive/Colab Notebooks/gwz_orders_samples_other_format.csv",
    sep=";"
)

df_orders.head()

  \tdate_date\torders_id\tcustomers_id\tcountry\tdepartment\ttotal_quantity\ttotal_turnover
0   0\t2019-01-01\t571\t560\tFRANCE\t77.0\t52\t92.71
1   1\t2019-01-01\t287\t282\tFRANCE\t17.0\t19\t97.94
2   2\t2019-01-01\t113\t113\tFRANCE\t50.0\t20\t94.15
3    3\t2019-01-01\t519\t510\tFRANCE\t22.0\t8\t73.78
4    4\t2019-01-01\t224\t222\tFRANCE\t13.0\t2\t27.99

3) Verileri düzgün bir şekilde yükledikten sonra, pazarlama ekibinin kullanabileceği yeni bir `gwz_orders_samples_other_format_clean.csv` dosyasına aktarın.


<details>
<summary> İpucu 🔍 </summary>
csv dosyasının bir dizin içermesi gerekmez.
Ayrıca kullanılan ayırıcıyı da kontrol etmelisiniz!

</details>

In [8]:
df_orders.to_csv(
    "/content/drive/MyDrive/Colab Notebooks/gwz_orders_samples_other_format_clean.csv",
    index=False,
    sep=";"
)

CSV dosyaları bazen yanıltıcı olabilir, ancak bu sorunlar Python ile çözülebilir!

## Json dosyalarıyla çalışma

Aşağıdaki hücreyi çalıştırarak `d` sözlüğünü başlatın.

In [9]:
d = {"firstname": "leonardo",
     "lastname": "dicaprio",
     "job": "actor"}

`d` klasöründen `actors.json` adlı bir dosya oluşturun. Sözdizimi konusunda kafanız karıştıysa ders notlarına bakabilirsiniz.

In [20]:
import json

with open ("/content/drive/MyDrive/Colab Notebooks/actors.json", "w") as f:
  json.dump(d, f, ensure_ascii=False, indent=2)

Yeni `actors.json` dosyasını açın ve yeni bir anahtar `nationality` ekleyin (Leonardo Dicaprio Amerikalıdır). \
Sonucu aynı dosya adına kaydedin. Dosyanızı kontrol edin.

In [21]:
import json

with open("/content/drive/MyDrive/Colab Notebooks/actors.json", "r", encoding="utf-8") as f:
    data = json.load(f)

data["nationality"] = "American"

with open("/content/drive/MyDrive/Colab Notebooks/actors.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(data)

{'firstname': 'leonardo', 'lastname': 'dicaprio', 'job': 'actor', 'nationality': 'American'}

## Excel dosyalarıyla çalışma

Bu bölümde, birden fazla


---


restoranın sahibi olduğunuzu hayal edin. Şu anda muhasebenizi Excel'de yapıyorsunuz.

[Excel dosyasını](https://docs.google.com/spreadsheets/d/14plrU8ZCEAHyRu0Qzn127azKxjjWFsAn/edit?usp=sharing&ouid=111434424059470547068&rtpof=true&sd=true) indirin ve inceleyin.


Kaç tane sayfa var?
Ne tür veriler var?

Excel dosyasında 2 adet sayfa (sheet) bulunmaktadır: Restaurant1 ve Restaurant2.
Her iki sayfada da günlük bazda restoran finansal verileri yer almaktadır.
Bu veriler Date, Turnover (Ciro), Cost (Maliyet) ve Margin (Kâr) sütunlarından oluşmaktadır.
Sayfalar farklı restoranlara ait günlük gelir–gider performansını göstermektedir.

Excel dosyasını Google Colab ortamınıza aktarın.
Verileri *ilk sayfadan* `df_sales_restaurant_1` DataFrame'e yükleyin.

In [25]:
import pandas as pd

df_sales_restaurant_1 = pd.read_excel(
    "/content/drive/MyDrive/Colab Notebooks/restaurants_accountability.xlsx",
    sheet_name="Restaurant1"
)

df_sales_restaurant_1.head()

        Date  Turnover  Cost  Margin
0 2021-12-01      1500  1200     300
1 2021-12-02      1200   900     300
2 2021-12-03      1900  1200     700
3 2021-12-04      2300  1500     800
4 2021-12-05      2100  1100    1000


Pandas ile bir Excel dosyasındaki tüm sayfaları nasıl listeleyebilirsiniz?




<details>
<summary> İpucu 🔍 </summary>

`pd.ExcelFile()` [belgeleri](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.ExcelFile.html) yardımcı olabilir ...
</details>

In [26]:
import pandas as pd

excel_file = pd.ExcelFile("/content/drive/MyDrive/Colab Notebooks/restaurants_accountability.xlsx")

excel_file.sheet_names

['Restaurant1', 'Restaurant2']


Şimdi, *ikinci sayfadaki* verileri `df_sales_restaurant_2` adlı bir veri çerçevesine yükleyin.




<details>
<summary> İpucu 🔍 </summary>
Erişmek istediğiniz sayfayı nasıl seçebilirsiniz? Şüpheniz varsa belgelere veya StackOverflow'a bakın.
</details>

In [27]:
df_sales_restaurant_2 = pd.read_excel(
    "/content/drive/MyDrive/Colab Notebooks/restaurants_accountability.xlsx",
    sheet_name="Restaurant2"
)

df_sales_restaurant_2.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Date,Turnover,Cost,Margin
3,NaN,NaN,2021-12-01 00:00:00,700,600,100
4,NaN,NaN,2021-12-02 00:00:00,920,540,380

Bu veri çerçevesinde olağandışı bir şey fark ettiniz mi? Excel dosyasındaki sayfayı tekrar inceleyin ve bu garip formatın nedenini anlamaya çalışın.

İkinci sayfadaki (Restaurant2) veriler düzgün formatta değildir.
İlk birkaç satır tamamen boş (NaN) olarak gelmiştir ve gerçek sütun başlıkları (Date, Turnover, Cost, Margin) üçüncü satırda yer almaktadır.
Bu nedenle Pandas sütun isimlerini Unnamed: 0, Unnamed: 1 gibi otomatik adlandırmıştır.
Veriyi doğru şekilde yüklemek için skiprows veya header parametresi kullanılarak başlık satırı doğru şekilde tanımlanmalıdır.

Verileri doğru şekilde yüklemek için önceki kod satırınızı değiştirin. \
Şüpheleriniz varsa [belgelere](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html) göz atın.

In [29]:
df_sales_restaurant_2 = pd.read_excel(
    "/content/drive/MyDrive/Colab Notebooks/restaurants_accountability.xlsx",
    sheet_name="Restaurant2",
    skiprows=2
)

df_sales_restaurant_2.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,Date,Turnover,Cost,Margin
1,NaN,NaN,2021-12-01 00:00:00,700,600,100
2,NaN,NaN,2021-12-02 00:00:00,920,540,380
3,NaN,NaN,2021-12-03 00:00:00,810,600,210
4,NaN,NaN,2021-12-04 00:00:00,1000,300,700

In [30]:
# Boş ilk iki sütunu at
df_sales_restaurant_2 = df_sales_restaurant_2.iloc[:, 2:]

# Kolon isimlerini düzelt
df_sales_restaurant_2.columns = ["Date", "Turnover", "Cost", "Margin"]

df_sales_restaurant_2.head()

                  Date  Turnover  Cost  Margin
0                 Date  Turnover  Cost  Margin
1  2021-12-01 00:00:00       700   600     100
2  2021-12-02 00:00:00       920   540     380
3  2021-12-03 00:00:00       810   600     210
4  2021-12-04 00:00:00      1000   300     700

Her veri çerçevesine yeni bir `restaurant_id` sütunu ekleyin (restaurant_1 için id = 1 ve restaurant_2 için id = 2) ve iki veri çerçevesini `df_sales` adlı tek bir veri çerçevesi halinde birleştirin.


İki veri çerçevesini birleştireceğiniz `eksen`e dikkat edin.

In [32]:
df_sales_restaurant_1["restaurant_id"] = 1
df_sales_restaurant_2["restaurant_id"] = 2

In [33]:
df_sales = pd.concat(
    [df_sales_restaurant_1, df_sales_restaurant_2],
    axis=0,
    ignore_index=True
)

df_sales.head()

                  Date Turnover  Cost Margin  restaurant_id
0  2021-12-01 00:00:00     1500  1200    300              1
1  2021-12-02 00:00:00     1200   900    300              1
2  2021-12-03 00:00:00     1900  1200    700              1
3  2021-12-04 00:00:00     2300  1500    800              1
4  2021-12-05 00:00:00     2100  1100   1000              1

Birleştirilmiş veri çerçevesini, `All` adlı bir sayfada yeni bir `restaurants_accountability_full.xlsx` dosyasına aktarın.

In [34]:

output_path = "/content/drive/MyDrive/Colab Notebooks/restaurants_accountability_full.xlsx"

with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
    df_sales.to_excel(writer, sheet_name="ALL", index=False)

print("Kaydedildi:", output_path)

Kaydedildi: /content/drive/MyDrive/Colab Notebooks/restaurants_accountability_full.xlsx